"""SPEC macro maker for surface diffraction runs.

Builds plain SPEC command files (run them with `qdo file.mac`, or wrap them in a `def` with
wrap_def). The command templates are settings, so beamline-specific commands (shutters, filters,
potentiostat, energy) slot in without code changes.

    s = MacroSettings(count="ct {t:g}", rock="dscan phi -{hw:g} {hw:g} {n} {t:g}")
    text = rod_macro([(0, 1), (1, 0)], s, L_min=0.3, L_max=4.0, step=0.02, bragg=bragg_for(model))
    write_macro("rods.mac", text)

Placeholders: {h} {k} {l} (reflection), {t} (count time, s), {hw} {n} (rocking half width and
points), {v} (potential, V), {e} (energy, keV), {s} (seconds to wait).
"""
import math
import time
from dataclasses import asdict, dataclass, field

import numpy as np


@dataclass
class MacroSettings:
    move: str = "br {h:g} {k:g} {l:.4f}"
    count: str = "ct {t:g}"
    rock: str = ""                         # e.g. "dscan phi -{hw:g} {hw:g} {n} {t:g}"; empty: count only
    rock_half_width: float = 0.5           # degrees
    rock_points: int = 21
    set_potential: str = "potset {v:.3f}"  # replace with the beamline's potentiostat macro
    set_energy: str = "moveE {e:.4f}"
    wait: str = "sleep({s:g})"
    before_rod: str = ""                   # e.g. "fon" ; each may hold several lines separated by ;
    after_rod: str = ""
    before_point: str = ""
    comment: str = "#"
    overhead_s: float = 4.0                # per point, for the time estimate (motion, readout)

    def to_dict(self):
        return asdict(self)


@dataclass
class Macro:
    lines: list = field(default_factory=list)
    count_s: float = 0.0
    n_points: int = 0
    overhead_s: float = 0.0
    title: str = ""

    def add(self, text):
        for part in str(text).split(";"):
            if part.strip():
                self.lines.append(part.strip())

    @property
    def seconds(self):
        return self.count_s + self.overhead_s

    def text(self, title=""):
        hdr = [f"# {title}" if title else "# SPEC macro",
               f"# generated by ctrfit {time.strftime('%Y-%m-%d %H:%M')}",
               f"# {self.n_points} points, counting {self.count_s / 60:.1f} min, estimated total "
               f"{self.seconds / 3600:.2f} h (with overhead)"]
        return "\n".join(hdr + self.lines) + "\n"


def _point(m, s, h, k, l, t):
    if s.before_point:
        m.add(s.before_point)
    m.add(s.move.format(h=h, k=k, l=l))
    if s.rock:
        m.add(s.rock.format(h=h, k=k, l=l, t=t, hw=s.rock_half_width, n=s.rock_points))
        m.count_s += t * s.rock_points
    else:
        m.add(s.count.format(h=h, k=k, l=l, t=t))
        m.count_s += t
    m.overhead_s += s.overhead_s * (s.rock_points if s.rock else 1)
    m.n_points += 1


def rod_L_points(L_min, L_max, step, bragg=(), exclude=0.05, fine_step=None, fine_window=0.3):
    """L values along a rod: `step`, finer (fine_step) within fine_window of Bragg peaks, and no
    points within `exclude` of them (the detector would saturate)."""
    L = list(np.arange(L_min, L_max + 1e-9, step))
    if fine_step:
        for b in bragg:
            lo = math.ceil((b - fine_window) / fine_step - 1e-9) * fine_step
            L += list(np.arange(lo, b + fine_window + 1e-9, fine_step))
    L = np.unique(np.round([x for x in L if L_min - 1e-9 <= x <= L_max + 1e-9], 6))
    for b in bragg:
        L = L[np.abs(L - b) >= exclude]
    return L


def count_times(I, t_base=1.0, t_min=1.0, t_max=60.0, power=1.0):
    """Count time per point to even out the statistics: t = t_base (I_median / I)^power, clipped."""
    I = np.maximum(np.asarray(I, float), 1e-12)
    return np.clip(t_base * (np.median(I) / I) ** power, t_min, t_max)


def bragg_for(model_or_ctr, H, K, L_max):
    """Bragg L positions (substrate and film) on a rod from a Model or CTRModel."""
    m = model_or_ctr.engine()[0] if hasattr(model_or_ctr, "engine") else model_or_ctr
    sub, film = m.bragg_L(H, K, L_max)
    return np.concatenate([sub, film])


def _intensity(model, H, K, L):
    """|F|^2 from a ctrfit Model (its current parameters) or a CTRModel (its surface state for plots)."""
    if hasattr(model, "params"):
        return model.intensity(H, K, L)
    from ..core.settings import parse_comp
    return model.intensity(H, K, L, parse_comp(model.p["comp_default"]))


def rod_macro(rods, settings=None, L_min=0.3, L_max=4.0, step=0.02, t=1.0, model=None, exclude=0.05,
              fine_step=None, fine_window=0.3, scale_times=False, t_min=1.0, t_max=60.0, title="rod scans"):
    """Scan each rod (H, K) point by point. With a model, Bragg peaks are avoided and (scale_times)
    count times follow 1/I so weak anti-Bragg points get more time."""
    s = settings or MacroSettings()
    m = Macro()
    for H, K in rods:
        bragg = bragg_for(model, H, K, L_max + 1) if model is not None else []
        L = rod_L_points(L_min, L_max, step, bragg, exclude if len(bragg) else 0.0, fine_step, fine_window)
        if model is not None and scale_times:
            times = count_times(_intensity(model, H, K, L), t, t_min, t_max)
        else:
            times = np.full(L.size, float(t))
        m.lines.append(f"{s.comment} rod ({H} {K} L): {L.size} points, L {L.min():.3f} to {L.max():.3f}"
                       + (f", Bragg peaks at {', '.join(f'{b:.3f}' for b in bragg)}" if len(bragg) else ""))
        if s.before_rod:
            m.add(s.before_rod)
        for l, ti in zip(L, times):
            _point(m, s, H, K, float(l), float(round(ti, 1)))
        if s.after_rod:
            m.add(s.after_rod)
    m.title = title
    return m


def points_macro(points, settings=None, t=1.0, title="fixed points"):
    """Count at a list of (H, K, L) or {label: (H, K, L)} points (e.g. the sensitivity ranking)."""
    s = settings or MacroSettings()
    m = Macro()
    items = points.items() if isinstance(points, dict) else ((f"({h} {k} {l:g})", (h, k, l)) for h, k, l in points)
    for lab, (h, k, l) in items:
        m.lines.append(f"{s.comment} {lab}")
        _point(m, s, h, k, float(l), float(t))
    m.title = title
    return m


def potential_macro(potentials, inner, settings=None, wait_s=60.0, title="potential series"):
    """For each potential: set it, wait, then run `inner` (a Macro, e.g. points_macro(...))."""
    s = settings or MacroSettings()
    m = Macro()
    for v in potentials:
        m.lines.append(f"{s.comment} ---- potential {v:g} V")
        m.add(s.set_potential.format(v=v))
        if wait_s:
            m.add(s.wait.format(s=wait_s))
            m.overhead_s += wait_s
        m.lines += inner.lines
        m.count_s += inner.count_s
        m.overhead_s += inner.overhead_s
        m.n_points += inner.n_points
    m.title = title
    return m


def energy_macro(hkl, energies, settings=None, t=1.0, title="energy scan"):
    """Fixed-q energy scan (anomalous): change energy, move back to (H K L) (angles change), count."""
    s = settings or MacroSettings()
    m = Macro()
    h, k, l = hkl
    for e in energies:
        m.add(s.set_energy.format(e=e))
        _point(m, s, h, k, float(l), float(t))
    m.title = title
    return m


def wrap_def(name, text):
    """Wrap a command list in a SPEC macro definition: def name '...'."""
    if not name.isidentifier():
        raise ValueError("macro name must be a plain identifier")
    body = "\n".join("    " + ln for ln in text.splitlines() if ln.strip() and not ln.startswith("#"))
    head = "\n".join(ln for ln in text.splitlines() if ln.startswith("#"))
    return f"{head}\ndef {name} '\n{body}\n'\n"


def write_macro(path, macro_or_text, title=None):
    text = macro_or_text if isinstance(macro_or_text, str) else macro_or_text.text(
        title or getattr(macro_or_text, "title", ""))
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    return path


def duration_text(seconds):
    h, rem = divmod(int(math.ceil(seconds)), 3600)
    return f"{h} h {rem // 60:02d} min"
